[mcp_servers.filesystem]
command = "npx"
args = [
    "-y",
    "@modelcontextprotocol/server-filesystem",
    'D:\Projects\Solo Suite',
]

[mcp_servers.next-devtools]
command = "npx"
args = [
    "-y",
    "next-devtools-mcp@latest",
]
