'use client'

import { useState, useCallback, useEffect } from 'react'
import { Building2, Check, ExternalLink, Mail, Plus, Search, Users, X } from 'lucide-react'
import type { ClientRecord } from '@/lib/database/types'

type Contact = { name?: string; email?: string }
const contactsFor = (client: ClientRecord): Contact[] => { try { const contacts = JSON.parse(client.contacts); return Array.isArray(contacts) ? contacts : [] } catch { return [] } }

export default function ClientsPage() {
  const [clients, setClients] = useState<ClientRecord[]>([])
  const [loading, setLoading] = useState(true)
  const [showNew, setShowNew] = useState(false)
  const [company, setCompany] = useState('')
  const [contactName, setContactName] = useState('')
  const [contactEmail, setContactEmail] = useState('')
  const [query, setQuery] = useState('')
  const load = useCallback(() => { fetch('/api/clients').then((res) => res.json()).then((data) => { setClients(data); setLoading(false) }).catch(() => setLoading(false)) }, [])
  useEffect(() => { load() }, [load])
  async function createClient() { if (!company.trim()) return; await fetch('/api/clients', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ company: company.trim(), contacts: JSON.stringify([{ name: contactName.trim(), email: contactEmail.trim() }]) }) }); setCompany(''); setContactName(''); setContactEmail(''); setShowNew(false); load() }
  const visibleClients = clients.filter((client) => `${client.company} ${client.contacts} ${client.tags ?? ''}`.toLowerCase().includes(query.toLowerCase()))
  if (loading) return <div className="flex flex-1 items-center justify-center text-sm text-zinc-600">Loading clients…</div>
  return <div className="min-h-full w-full bg-zinc-50/70 p-4 sm:p-6 dark:bg-zinc-950"><div className="mx-auto max-w-[1400px]">
    <header className="mb-7 flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><p className="mb-2 text-xs font-semibold uppercase tracking-[0.18em] text-emerald-700 dark:text-emerald-400">CRM · Relationships</p><h1 className="text-3xl font-semibold tracking-tight text-zinc-950 dark:text-white">Clients, with context.</h1><p className="mt-2 text-sm text-zinc-600 dark:text-zinc-400 dark:text-zinc-600">A calm home for every active relationship and its key people.</p></div><button onClick={() => setShowNew(true)} className="inline-flex items-center justify-center gap-2 rounded-xl bg-emerald-700 px-4 py-2.5 text-sm font-semibold text-white shadow-sm shadow-emerald-700/20 transition hover:-translate-y-0.5 hover:bg-emerald-800"><Plus className="size-4" /> Add client</button></header>
    <section className="mb-6 grid gap-3 sm:grid-cols-2"><Summary icon={<Building2 className="size-4" />} value={clients.length} label="Client accounts" /><Summary icon={<Users className="size-4" />} value={clients.reduce((total, client) => total + contactsFor(client).length, 0)} label="People in your network" /></section>
    <div className="mb-5 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div className="relative max-w-sm flex-1"><Search className="pointer-events-none absolute left-3 top-1/2 size-4 -translate-y-1/2 text-zinc-600" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search clients, people, or tags" className="w-full rounded-xl border border-zinc-200 bg-white py-2.5 pl-9 pr-4 text-sm outline-none transition focus:border-emerald-500 focus:ring-4 focus:ring-emerald-500/10 dark:border-zinc-800 dark:bg-zinc-900 dark:text-white" /></div><p className="text-sm text-zinc-600 dark:text-zinc-400"><span className="font-medium text-zinc-900 dark:text-white">{visibleClients.length}</span> visible</p></div>
    {showNew && <form onSubmit={(event) => { event.preventDefault(); createClient() }} className="animate-in mb-6 rounded-2xl border border-emerald-100 bg-white p-4 shadow-sm dark:border-emerald-900/70 dark:bg-zinc-900"><div className="mb-4 flex items-center justify-between"><div><h2 className="font-semibold text-zinc-900 dark:text-white">Add a client</h2><p className="text-sm text-zinc-600 dark:text-zinc-400">Create the account and its primary contact.</p></div><button type="button" onClick={() => setShowNew(false)} className="rounded-lg p-2 text-zinc-600 hover:bg-zinc-100 dark:hover:bg-zinc-800" aria-label="Close form"><X className="size-4" /></button></div><div className="grid gap-3 md:grid-cols-3"><input autoFocus required value={company} onChange={(event) => setCompany(event.target.value)} placeholder="Company name" className="rounded-xl border border-zinc-200 bg-zinc-50 px-3 py-2.5 text-sm outline-none focus:border-emerald-500 focus:ring-4 focus:ring-emerald-500/10 dark:border-zinc-700 dark:bg-zinc-800 dark:text-white" /><input value={contactName} onChange={(event) => setContactName(event.target.value)} placeholder="Primary contact" className="rounded-xl border border-zinc-200 bg-zinc-50 px-3 py-2.5 text-sm outline-none focus:border-emerald-500 focus:ring-4 focus:ring-emerald-500/10 dark:border-zinc-700 dark:bg-zinc-800 dark:text-white" /><input value={contactEmail} onChange={(event) => setContactEmail(event.target.value)} type="email" placeholder="Email address" className="rounded-xl border border-zinc-200 bg-zinc-50 px-3 py-2.5 text-sm outline-none focus:border-emerald-500 focus:ring-4 focus:ring-emerald-500/10 dark:border-zinc-700 dark:bg-zinc-800 dark:text-white" /></div><div className="mt-4 flex justify-end gap-2"><button type="button" onClick={() => setShowNew(false)} className="rounded-lg px-3 py-2 text-sm font-medium text-zinc-600 hover:bg-zinc-100 dark:text-zinc-300 dark:hover:bg-zinc-800">Cancel</button><button className="rounded-lg bg-emerald-700 px-3 py-2 text-sm font-semibold text-white hover:bg-emerald-800">Create client</button></div></form>}
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{visibleClients.map((client) => <ClientCard key={client.id} client={client} />)}{visibleClients.length === 0 && <div className="col-span-full rounded-2xl border border-dashed border-zinc-300 py-16 text-center dark:border-zinc-700"><Building2 className="mx-auto size-6 text-zinc-300" /><p className="mt-3 text-sm font-medium text-zinc-600 dark:text-zinc-300">No matching clients</p><p className="mt-1 text-sm text-zinc-600">Try another search or add your first client.</p></div>}</section>
  </div></div>
}

function Summary({ icon, value, label }: { icon: React.ReactNode; value: number; label: string }) { return <div className="flex items-center gap-3 rounded-2xl border border-zinc-200 bg-white p-4 shadow-sm dark:border-zinc-800 dark:bg-zinc-900"><span className="rounded-xl bg-emerald-50 p-2.5 text-emerald-700 dark:bg-emerald-950/60 dark:text-emerald-400">{icon}</span><div><p className="text-xl font-semibold text-zinc-950 dark:text-white">{value}</p><p className="text-sm text-zinc-600 dark:text-zinc-400">{label}</p></div></div> }
function ClientCard({ client }: { client: ClientRecord }) { const contacts = contactsFor(client); return <article className="group rounded-2xl border border-zinc-200 bg-white p-5 shadow-sm transition duration-200 hover:-translate-y-0.5 hover:border-emerald-200 hover:shadow-md dark:border-zinc-800 dark:bg-zinc-900 dark:hover:border-emerald-900"><div className="flex items-start justify-between gap-3"><span className="flex size-11 items-center justify-center rounded-xl bg-zinc-100 text-sm font-semibold text-zinc-600 dark:bg-zinc-800 dark:text-zinc-300">{client.company.slice(0, 2).toUpperCase()}</span><div className="flex gap-1">{client.portalAccess && <span title="Portal access enabled" className="rounded-lg bg-emerald-50 p-2 text-emerald-700 dark:bg-emerald-950/60"><Check className="size-3.5" /></span>}<ExternalLink className="mt-2 size-3.5 text-zinc-300 transition group-hover:text-emerald-700" /></div></div><h2 className="mt-4 text-base font-semibold text-zinc-900 dark:text-white">{client.company}</h2><div className="mt-3 min-h-11 space-y-1.5">{contacts.slice(0, 2).map((contact, index) => <div key={index} className="text-sm"><p className="text-zinc-600 dark:text-zinc-300">{contact.name || 'Unnamed contact'}</p>{contact.email && <p className="flex items-center gap-1 text-xs text-zinc-600"><Mail className="size-3" />{contact.email}</p>}</div>)}{contacts.length === 0 && <p className="text-sm text-zinc-600">No contacts added</p>}</div>{client.tags && <div className="mt-4 flex flex-wrap gap-1.5">{client.tags.split(',').filter(Boolean).map((tag) => <span key={tag} className="rounded-md bg-zinc-100 px-2 py-1 text-[11px] font-medium text-zinc-600 dark:bg-zinc-800 dark:text-zinc-300">{tag.trim()}</span>)}</div>}</article> }

